# Generated by Django 5.1 on 2024-08-17 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='p_emial',
            new_name='p_email',
        ),
    ]
